version: '2'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.1.0-incubating
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/root/logs
      - ./data/namesrv/store:/root/store
    command: sh mqnamesrv
  broker:
    image: rocketmqinc/rocketmq:4.1.0-incubating
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./data/broker/logs:/root/logs
      - ./data/broker/store:/root/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq-4.3.0/conf/broker.conf
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
