version: '2'
services:
  namesrv:
    image: apache/rocketmq-namesrv:4.2.0-compose
    container_name: rmqnamesrv
    build:
      context: ./rocketmq-namesrv
      args:
        - version=4.2.0
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/opt/logs
      - ./data/namesrv/store:/opt/store
  broker:
    image: apache/rocketmq-broker:4.2.0-compose
    container_name: rmqbroker
    build:
      context: ./rocketmq-broker
      args:
        - version=4.2.0
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./data/broker/logs:/opt/logs
      - ./data/broker/store:/opt/store
    depends_on:
      - namesrv
