apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketmq
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: rocketmq
    spec:
      containers:
      - name: broker
        image: apache/rocketmq-broker:4.3.0-k8s
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 10909
          - containerPort: 10911
        volumeMounts:
          - mountPath: /opt/logs
            name: brokeroptlogs
          - mountPath: /opt/store
            name: brokeroptstore
      - name: namesrv
        image: apache/rocketmq-namesrv:4.3.0-k8s
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9876
        volumeMounts:
          - mountPath: /opt/logs
            name: namesrvoptlogs
          - mountPath: /opt/store
            name: namesrvoptstore
      volumes:
      - name: brokeroptlogs
        hostPath:
          path: /data/broker/logs
      - name: brokeroptstore
        hostPath:
          path: /data/broker/store
      - name: namesrvoptlogs
        hostPath:
          path: /data/namesrv/logs
      - name: namesrvoptstore
        hostPath:
          path: /data/namesrv/store
      nodeSelector:
           rocketmq: "on"
